/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.daipc.form;

import com.daipc.enumm.HienThi;
import com.daipc.enumm.TrangThaiCRUD;
import static com.daipc.enumm.TrangThaiCRUD.ThanhCong;
import static com.daipc.enumm.TrangThaiCRUD.ThatBai;
import com.daipc.model.SanPham;
import com.daipc.repo.QuanLiSanPham;
import com.daipc.repo.Repository;
import com.daipc.swing.PanelBorder;
import com.daipc.table.TableCustom;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import com.daipc.swing.Button;

/**
 *
 * @author DaiPc
 */
public class Form_DanhSachAn extends javax.swing.JDialog {

    int selectedRow = -1;
    boolean updateTbl = false;
    List<SanPham> listSP;
    QuanLiSanPham QLSP = new QuanLiSanPham();
    DefaultTableModel modelSP = new DefaultTableModel(new String[]{"Mã Sản Phẩm", "Tên Sản Phẩm", "Mô Tả", "TrangThai"}, 10) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    public boolean isUpdateTbl() {
        return updateTbl;
    }

    public void setUpdateTbl(boolean updateTbl) {
        this.updateTbl = updateTbl;
    }

    /**
     * Creates new form Form_DanhSachAn
     */
    public Form_DanhSachAn(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        TableCustom.apply(scrollInfoProducts, TableCustom.TableType.DEFAULT);
        tblInfoProducts.setModel(modelSP);
        listSP = new ArrayList<>();
        loadDataToTable(modelSP, listSP, QLSP, "select * from SanPham where hienthi = ?", HienThi.An.name());
        if (selectedRow >= 0) {
            tblInfoProducts.setRowSelectionInterval(selectedRow, selectedRow);

        }
    }

    public void loadDataToTable(DefaultTableModel model, List<SanPham> list, Repository<SanPham> repo, String sqlQuery, Object... params) {
        model.setRowCount(0);
        list.clear();
        list.addAll(repo.select(sqlQuery, params));
        for (SanPham sp : list) {
            model.addRow(sp.getSanPham());
        }
        selectedRow = list.size() - 1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder1 = new com.daipc.swing.PanelBorder();
        scrollInfoProducts = new javax.swing.JScrollPane();
        tblInfoProducts = new javax.swing.JTable();
        btnHien = new com.daipc.swing.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Danh Sách Ẩn");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));

        panelBorder1.setBackground(new java.awt.Color(255, 255, 255));

        tblInfoProducts.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        tblInfoProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "null"
            }
        ) {
            final boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblInfoProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblInfoProductsMouseClicked(evt);
            }
        });
        scrollInfoProducts.setViewportView(tblInfoProducts);

        btnHien.setText("Hiện");
        btnHien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollInfoProducts, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnHien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollInfoProducts, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnHien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblInfoProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblInfoProductsMouseClicked
        selectedRow = tblInfoProducts.getSelectedRow();
        tblInfoProducts.setRowSelectionInterval(selectedRow, selectedRow);
    }//GEN-LAST:event_tblInfoProductsMouseClicked

    private void btnHienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHienActionPerformed
        int id = listSP.get(selectedRow).getId();
        TrangThaiCRUD status = QLSP.update("update SanPham set hienthi = ? where id = ?", HienThi.Hien.name(), id);
        switch (status) {
            case ThanhCong:
                loadDataToTable(modelSP, listSP, QLSP, "select * from SanPham where hienthi = ?", HienThi.An.name());
                System.out.println(selectedRow);
                if (selectedRow >= 0) {
                    tblInfoProducts.setRowSelectionInterval(selectedRow, selectedRow);
                }
                updateTbl = true;
                break;
            case ThatBai:

            default:
        }
//        tblInfoProducts.setRowSelectionInterval(selectedRow, selectedRow);
    }//GEN-LAST:event_btnHienActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_DanhSachAn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_DanhSachAn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_DanhSachAn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_DanhSachAn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Form_DanhSachAn dialog = new Form_DanhSachAn(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.daipc.swing.Button btnHien;
    private com.daipc.swing.PanelBorder panelBorder1;
    private javax.swing.JScrollPane scrollInfoProducts;
    private javax.swing.JTable tblInfoProducts;
    // End of variables declaration//GEN-END:variables
}
