/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.daipc.form;

import com.daipc.model.ChiTietSP;
import com.daipc.model.Voucher;
import com.daipc.repo.VoucherRepo;
import java.awt.Color;
import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DaiPc
 */
public class Form_Promotion extends javax.swing.JPanel {

    VoucherRepo vr = new VoucherRepo();
    private DefaultTableModel modelVC;
    private DefaultComboBoxModel modelCbb;
    private List<Voucher> listVC;

    /**
     * Creates new form Form_Promotion
     */
    public Form_Promotion() {
        initComponents();
        init();
//        setborde();
      

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder1 = new com.daipc.swing.PanelBorder();
        cbb_TrangThai = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        cbb_searchVoucher = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Voucher = new javax.swing.JTable();
        btnadd = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        date_batdau = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        date_ketthuc = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtgiatritoidavoucher = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtma = new javax.swing.JTextField();
        txtsoluong = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtmota = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();

        panelBorder1.setBackground(new java.awt.Color(255, 255, 255));

        cbb_TrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Đang diễn ra ", "Sắp diễn ra ", "Đã diễn ra" }));
        cbb_TrangThai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbb_TrangThaiActionPerformed(evt);
            }
        });

        jLabel1.setText("Trạng thái");

        jButton2.setText("Bỏ Lọc");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        cbb_searchVoucher.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Dưới 500.000đ", "500.000 - 1 triệu", "1 - 2 triệu ", "Giá trên 3 triệu " }));
        cbb_searchVoucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbb_searchVoucherActionPerformed(evt);
            }
        });

        jLabel9.setText("Voucher  ");

        tbl_Voucher.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã Voucher", "Giá trị Voucher", "Ngày bắt đầu", "Ngày kết thúc", "Số lượng", "Mô Tả", "Trạng Thái"
            }
        ));
        tbl_Voucher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_VoucherMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_Voucher);

        btnadd.setBackground(new java.awt.Color(51, 153, 255));
        btnadd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnadd.setText("ADD");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btnreset.setBackground(new java.awt.Color(51, 153, 255));
        btnreset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnreset.setText("RESET");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        btndelete.setBackground(new java.awt.Color(51, 153, 255));
        btndelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btndelete.setText("DELETE");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnupdate.setBackground(new java.awt.Color(51, 153, 255));
        btnupdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnupdate.setText("UPDATE");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Thời gian bắt đầu");

        date_batdau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                date_batdauMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Thời gian kết thúc");

        date_ketthuc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                date_ketthucMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Mô tả voucher ");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Giá trị  voucher ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Số lượng");

        txtgiatritoidavoucher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtgiatritoidavoucherMouseClicked(evt);
            }
        });
        txtgiatritoidavoucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgiatritoidavoucherActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Mã voucher");

        txtma.setEditable(false);

        txtsoluong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtsoluongMouseClicked(evt);
            }
        });
        txtsoluong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsoluongActionPerformed(evt);
            }
        });

        txtmota.setColumns(20);
        txtmota.setRows(5);
        txtmota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtmotaMouseClicked(evt);
            }
        });
        txtmota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtmotaKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(txtmota);

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel3.setText("QUẢN LÝ Voucher");

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtma, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtgiatritoidavoucher, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(date_batdau, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(date_ketthuc, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnreset, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(90, Short.MAX_VALUE))
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(cbb_searchVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(cbb_TrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jButton2)
                .addGap(30, 30, 30))
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addComponent(date_batdau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(date_ketthuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(txtgiatritoidavoucher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)))
                .addGap(18, 18, 18)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnadd)
                        .addComponent(btnreset)
                        .addComponent(btnupdate)
                        .addComponent(btndelete)))
                .addGap(18, 18, 18)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbb_searchVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jButton2)
                    .addComponent(jLabel1)
                    .addComponent(cbb_TrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btnresetActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        Boolean chech = check();
        if (chech) {
            int coHoi = JOptionPane.showConfirmDialog(this, "Bạn có muốn thêm không?", "", JOptionPane.YES_NO_OPTION);
            if (coHoi == JOptionPane.YES_OPTION) {
                Voucher voucher = new Voucher();
                List<Voucher> list = vr.getAll();
                String maVoucher = "";
                for (Voucher vc : list) {
                    maVoucher = "VC" + vc.getId();
                }
                String mota = txtmota.getText();
                Integer soLuong = Integer.parseInt(txtsoluong.getText());
                String giatri = (txtgiatritoidavoucher.getText());
                BigDecimal gTVC = new BigDecimal(giatri);
                Date batDau = date_batdau.getDate();
                Date KetThuc = date_ketthuc.getDate();
                java.util.Date StartDate = date_batdau.getDate();
                java.util.Date EndDate = date_ketthuc.getDate();
                java.util.Date ngayTao = new Date();
                //        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                //            sdf.setLenient(false);
                //            try {
                //                StartDate = sdf.parse(batDau);
                //                EndDate = sdf.parse(KetThuc);
                //
                //            } catch (Exception e) {
                //                JOptionPane.showMessageDialog(this, "Khong dung dinh dang ");
                //                return;
                //            }
                int trangthai = 1;

                if (ngayTao.getTime() >= StartDate.getTime() && ngayTao.getTime() < EndDate.getTime()) {
                    trangthai = 2;
                } else if (ngayTao.getTime() >= EndDate.getTime()) {
                    trangthai = 3;
                } else if (ngayTao.getTime() < StartDate.getTime()) {
                    trangthai = 1;
                }

                Voucher v = new Voucher(maVoucher, gTVC, batDau, KetThuc, soLuong, mota, trangthai);
                vr.addVoucher(v);
                reset();
                init();
                JOptionPane.showMessageDialog(this, "Thêm thành công", "", JOptionPane.INFORMATION_MESSAGE);
                System.out.println(maVoucher);
                System.out.println(mota);
            }else{
                JOptionPane.showMessageDialog(this, "Thêm thất bại ", "", JOptionPane.WARNING_MESSAGE);
            }

        }


    }//GEN-LAST:event_btnaddActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        String ma = txtma.getText();
        vr.delete(ma);
        init();
        reset();
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        String maVoucher = txtma.getText();
        String mota = txtmota.getText();
        Integer soLuong = Integer.parseInt(txtsoluong.getText());
        String giatri = txtgiatritoidavoucher.getText();
        BigDecimal gTVC = new BigDecimal(giatri);
        Date batDau = date_batdau.getDate();
        Date KetThuc = date_ketthuc.getDate();
        java.util.Date StartDate = date_batdau.getDate();
        java.util.Date EndDate = date_ketthuc.getDate();
        java.util.Date ngayTao = new Date();
        //        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        //            sdf.setLenient(false);
        //            try {
        //                StartDate = sdf.parse(batDau);
        //                EndDate = sdf.parse(KetThuc);
        //
        //            } catch (Exception e) {
        //                JOptionPane.showMessageDialog(this, "Khong dung dinh dang ");
        //                return;
        //            }
        int trangthai = 1;

        if (ngayTao.getTime() >= StartDate.getTime() && ngayTao.getTime() < EndDate.getTime()) {
            trangthai = 2;
        } else if (ngayTao.getTime() >= EndDate.getTime()) {
            trangthai = 3;
        } else if (ngayTao.getTime() < StartDate.getTime()) {
            trangthai = 1;
        }

        Voucher v = new Voucher(maVoucher, gTVC, StartDate, EndDate, soLuong, mota, trangthai);
        vr.updateVoucher(v);
        init();
        reset();
    }//GEN-LAST:event_btnupdateActionPerformed

    private void txtgiatritoidavoucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgiatritoidavoucherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgiatritoidavoucherActionPerformed

    private void txtsoluongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsoluongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsoluongActionPerformed

    private void tbl_VoucherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_VoucherMouseClicked
        // TODO add your handling code here:
        int row = tbl_Voucher.getSelectedRow();
        String ma = tbl_Voucher.getValueAt(row, 1).toString();
        String GiaTri = tbl_Voucher.getValueAt(row, 2).toString();
        String strNgayBatDau = tbl_Voucher.getValueAt(row, 3).toString();
        String strNgayKetThuc = tbl_Voucher.getValueAt(row, 4).toString();
        String SoLuong = tbl_Voucher.getValueAt(row, 5).toString();
        String moTa = tbl_Voucher.getValueAt(row, 6).toString();
        String TrangThai = tbl_Voucher.getValueAt(row, 7).toString();

        Date NgayBD;
        Date NgayKT;
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        sdf.setLenient(false);
        try {
            NgayBD = sdf.parse(strNgayBatDau);
            NgayKT = sdf.parse(strNgayKetThuc);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Khong dung dinh dang ");
            return;
        }

        txtma.setText(ma);
        txtmota.setText(moTa);
        txtgiatritoidavoucher.setText(GiaTri);
        date_batdau.setDate(NgayBD);
        date_ketthuc.setDate(NgayKT);
        txtsoluong.setText(SoLuong);
    }//GEN-LAST:event_tbl_VoucherMouseClicked

    private void cbb_TrangThaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbb_TrangThaiActionPerformed
        // TODO add your handling code here:
        String cbbTT = String.valueOf(cbb_TrangThai.getSelectedItem());
        int TrangThai = 1;

        if (cbbTT.equals("Sắp diễn ra")) {
            TrangThai = 1;
        } else if (cbbTT.equals("Đang diễn ra ")) {
            TrangThai = 2;
        } else if (cbbTT.equals("Đã diễn ra")) {
            TrangThai = 3;
        }
        if (cbbTT.equals("Tất cả")) {
            init();
        } else {
            listVC = vr.seach(TrangThai);
            modelVC = (DefaultTableModel) tbl_Voucher.getModel();
            modelVC.setRowCount(0);
            int i = 1;
            String trangthai = "";

            for (Voucher voucher : listVC) {
                int trangThai = voucher.getTrangThai();
                if (trangThai == 1) {
                    trangthai = "Sắp diễn ra";
                } else if (trangThai == 2) {
                    trangthai = "Đang diễn ra";
                } else if (trangThai == 3) {
                    trangthai = "Đã diễn ra";
                }

                Object[] row = new Object[]{
                    i++,
                    voucher.getMaVoucher(),
                    voucher.getGiaTriVoucher(),
                    voucher.getNgayBatDau(),
                    voucher.getNgayKetThuc(),
                    voucher.getSoLuong(),
                    voucher.getMoTa(),
                    trangthai
                };
                modelVC.addRow(row);
            }
            System.out.println(TrangThai);

        }
    }//GEN-LAST:event_cbb_TrangThaiActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        cbb_searchVoucher.setSelectedItem("Tất cả");
        cbb_TrangThai.setSelectedItem("Tất cả");
        cbb_searchVoucher.setSelectedItem("");
        init();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtsoluongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtsoluongMouseClicked
        // TODO add your handling code here:
        txtsoluong.setBorder(BorderFactory.createLineBorder(Color.LIGHT_GRAY));
    }//GEN-LAST:event_txtsoluongMouseClicked

    private void txtgiatritoidavoucherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtgiatritoidavoucherMouseClicked
        // TODO add your handling code here:
        txtgiatritoidavoucher.setBorder(BorderFactory.createLineBorder(Color.LIGHT_GRAY));
    }//GEN-LAST:event_txtgiatritoidavoucherMouseClicked

    private void date_ketthucMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_date_ketthucMouseClicked
        // TODO add your handling code here:
        date_ketthuc.setBorder(BorderFactory.createLineBorder(Color.LIGHT_GRAY));
    }//GEN-LAST:event_date_ketthucMouseClicked

    private void date_batdauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_date_batdauMouseClicked
        // TODO add your handling code here:
        date_batdau.setBorder(BorderFactory.createLineBorder(Color.LIGHT_GRAY));
    }//GEN-LAST:event_date_batdauMouseClicked

    private void txtmotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtmotaMouseClicked
        // TODO add your handling code here:
        txtsoluong.setBorder(BorderFactory.createLineBorder(Color.LIGHT_GRAY));
    }//GEN-LAST:event_txtmotaMouseClicked

    private void txtmotaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmotaKeyReleased
        // TODO add your handling code here:
        if (txtmota.getText() != null) {
            txtsoluong.setBorder(BorderFactory.createLineBorder(Color.LIGHT_GRAY));
        }

    }//GEN-LAST:event_txtmotaKeyReleased

    private void cbb_searchVoucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbb_searchVoucherActionPerformed
        // TODO add your handling code here:
        String cbbGiaNhap = String.valueOf(cbb_searchVoucher.getSelectedItem()).trim();
        BigDecimal giaN = null;
        if(cbbGiaNhap.equals("Tất cả")){
            init();
        }else {
            // Default price range
            int GiaNhapMin = 1000;
            int GiaNhapMax = 1000;
            BigDecimal MinGN = new BigDecimal(GiaNhapMin);
            BigDecimal MaxGN = new BigDecimal(GiaNhapMax);
            
            // Print the selected combo box value for debugging
            System.out.println("Selected combo box value: " + cbbGiaNhap);

            switch (cbbGiaNhap) {
                case "Dưới 500.000đ" -> {
                    System.out.println("Gia Nhap Min Duoi 500: 0");
                    GiaNhapMin = 0;
                    GiaNhapMax = 500000;
                }
                case "500.000 - 1 triệu" -> {
                    GiaNhapMin = 500000;
                    GiaNhapMax = 1000000;
                }
                case "1 - 2 triệu" -> {
                    GiaNhapMin = 1000000;
                    GiaNhapMax = 2000000;
                }
                case "Giá trên 3 triệu" -> {
                    GiaNhapMin = 3000000;
                    GiaNhapMax = giaN != null ? giaN.intValue() : 3000000;
                }
                default -> {
                    System.err.println("Unrecognized price range: " + cbbGiaNhap);
                }
            }

            // Convert updated int values to BigDecimal
            MinGN = BigDecimal.valueOf(GiaNhapMin);
            MaxGN = BigDecimal.valueOf(GiaNhapMax);

            // Print the results for verification
            System.out.println("GiaNhapMin: " + GiaNhapMin);
            System.out.println("GiaNhapMax: " + GiaNhapMax);
            System.out.println("MinGN: " + MinGN);
            System.out.println("MaxGN: " + MaxGN);
            System.out.println("Gia Max: " + giaN);

            listVC = vr.searchGiaTriVC(MinGN, MaxGN);
        modelVC = (DefaultTableModel) tbl_Voucher.getModel();
        modelVC.setRowCount(0);
        int i = 1;
        String trangthai = "";

        for (Voucher voucher : listVC) {
            int trangThai = voucher.getTrangThai();
            if (trangThai == 1) {
                trangthai = "Sắp diễn ra";
            } else if (trangThai == 2) {
                trangthai = "Đang diễn ra";
            } else if (trangThai == 3) {
                trangthai = "Đã diễn ra";
            }

            Object[] row = new Object[]{
                i++,
                voucher.getMaVoucher(),
                voucher.getGiaTriVoucher(),
                voucher.getNgayBatDau(),
                voucher.getNgayKetThuc(),
                voucher.getSoLuong(),
                voucher.getMoTa(),
                trangthai
            };
            modelVC.addRow(row);
        }
        System.out.println(MaxGN);
        

        }
            
        //        Dưới 500.000đ
        //500.0000 - 1 triệu
        //1 - 2 triệu
        //Giá trên 3 triệu
    }//GEN-LAST:event_cbb_searchVoucherActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnupdate;
    private javax.swing.JComboBox<String> cbb_TrangThai;
    private javax.swing.JComboBox<String> cbb_searchVoucher;
    private com.toedter.calendar.JDateChooser date_batdau;
    private com.toedter.calendar.JDateChooser date_ketthuc;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.daipc.swing.PanelBorder panelBorder1;
    private javax.swing.JTable tbl_Voucher;
    private javax.swing.JTextField txtgiatritoidavoucher;
    private javax.swing.JTextField txtma;
    private javax.swing.JTextArea txtmota;
    private javax.swing.JTextField txtsoluong;
    // End of variables declaration//GEN-END:variables

    public void init() {
        listVC = vr.getAll();
        modelVC = (DefaultTableModel) tbl_Voucher.getModel();
        modelVC.setRowCount(0);
        int i = 1;
        String trangthai = "";

        for (Voucher voucher : listVC) {
            int trangThai = voucher.getTrangThai();
            if (trangThai == 1) {
                trangthai = "Sắp diễn ra";
            } else if (trangThai == 2) {
                trangthai = "Đang diễn ra";
            } else if (trangThai == 3) {
                trangthai = "Đã diễn ra";
            }

            Object[] row = new Object[]{
                i++,
                voucher.getMaVoucher(),
                voucher.getGiaTriVoucher(),
                voucher.getNgayBatDau(),
                voucher.getNgayKetThuc(),
                voucher.getSoLuong(),
                voucher.getMoTa(),
                trangthai
            };
            modelVC.addRow(row);
        }

    }

    public void reset() {
        txtma.setText("");
        txtmota.setText("");
        txtsoluong.setText("");
        date_batdau.setDate(null);
        date_ketthuc.setDate(null);
        cbb_TrangThai.setSelectedItem("Tất cả");
        txtgiatritoidavoucher.setText("");
    }

    public Boolean check() {
        if (txtmota.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Dữ liệu không được bỏ trống ", "", JOptionPane.WARNING_MESSAGE);
//            txtmota.setBorder(BorderFactory.createLineBorder(Color.RED));

            return false;
        }

        if (txtgiatritoidavoucher.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Dữ liệu không được bỏ trống ", "", JOptionPane.WARNING_MESSAGE);
//            txtgiatritoidavoucher.setBorder(BorderFactory.createLineBorder(Color.RED));
            return false;
        }

        if (date_batdau.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Dữ liệu không được bỏ trống ", "", JOptionPane.WARNING_MESSAGE);
//            date_batdau.setBorder(BorderFactory.createLineBorder(Color.RED));
            return false;
        }

        if (date_ketthuc.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Dữ liệu không được bỏ trống ", "", JOptionPane.WARNING_MESSAGE);
//            date_ketthuc.setBorder(BorderFactory.createLineBorder(Color.RED));
            return false;
        }

        try {
            Integer soLuong = Integer.parseInt(txtsoluong.getText());
            if (soLuong <= 0) {
                JOptionPane.showMessageDialog(this, "Số lượng phải lớn hơn 0", "", JOptionPane.WARNING_MESSAGE);
//                txtsoluong.setBorder(BorderFactory.createLineBorder(Color.RED));
                return false;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Số lượng phải là số", "", JOptionPane.WARNING_MESSAGE);
//            txtsoluong.setBorder(BorderFactory.createLineBorder(Color.RED));
            return false;
        }
        return true;
    }

    public void setborde() {
        txtsoluong.setBorder(BorderFactory.createLineBorder(Color.LIGHT_GRAY));
        txtmota.setBorder(BorderFactory.createLineBorder(Color.LIGHT_GRAY));
        txtgiatritoidavoucher.setBorder(BorderFactory.createLineBorder(Color.LIGHT_GRAY));
        date_batdau.setBorder(BorderFactory.createLineBorder(Color.LIGHT_GRAY));
        date_ketthuc.setBorder(BorderFactory.createLineBorder(Color.LIGHT_GRAY));
    }

}
