-- ============================================================
-- Retail desktop app schema (PostgreSQL) - v2
-- Create the database separately, then connect to it and run this file:
--   CREATE DATABASE retail_db WITH ENCODING 'UTF8' TEMPLATE template0;
-- ============================================================

CREATE TABLE product (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE supplier (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    phone VARCHAR(15),
    address VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE color (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE size (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE material (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE thickness (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

-- ============================================================
-- Product variant (a product + color + size + material + thickness)
-- ============================================================
CREATE TABLE product_variant (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,              -- can double as barcode
    product_id INT NOT NULL REFERENCES product (id),
    color_id INT NOT NULL REFERENCES color (id),
    size_id INT NOT NULL REFERENCES size (id),
    material_id INT NOT NULL REFERENCES material (id),
    thickness_id INT NOT NULL REFERENCES thickness (id),
    supplier_id INT REFERENCES supplier (id),
    stock_quantity INT NOT NULL DEFAULT 0,
    cost_price NUMERIC(15, 0) NOT NULL DEFAULT 0,  -- VND, no decimals
    sale_price NUMERIC(15, 0) NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_variant_combo UNIQUE (
        product_id, color_id, size_id, material_id, thickness_id
    ),
    CONSTRAINT ck_variant_stock CHECK (stock_quantity >= 0),
    CONSTRAINT ck_variant_prices CHECK (cost_price >= 0 AND sale_price >= 0)
);

-- ============================================================
-- People
-- ============================================================
CREATE TABLE employee (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    full_name VARCHAR(255) NOT NULL,
    phone VARCHAR(15),
    birth_date DATE,
    role VARCHAR(20) NOT NULL DEFAULT 'STAFF',
    gender BOOLEAN,
    address VARCHAR(255),
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT ck_employee_role CHECK (role IN ('MANAGER', 'STAFF'))
);

CREATE TABLE customer (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    full_name VARCHAR(255) NOT NULL,
    phone VARCHAR(15) UNIQUE,
    gender BOOLEAN,
    address VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

INSERT INTO customer (code, full_name) VALUES ('KL', 'Khách lẻ');

-- ============================================================
-- Voucher
-- ============================================================
CREATE TABLE voucher (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    -- AMOUNT (VND) or PERCENT
    discount_type VARCHAR(10) NOT NULL DEFAULT 'AMOUNT',
    discount_value NUMERIC(15, 2) NOT NULL,
    -- minimum invoice total to apply
    min_order_amount NUMERIC(15, 0) NOT NULL DEFAULT 0,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    quantity INT NOT NULL DEFAULT 0,
    description TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT ck_voucher_type CHECK (discount_type IN ('AMOUNT', 'PERCENT')),
    CONSTRAINT ck_voucher_value CHECK (
        discount_value > 0
        AND (discount_type = 'AMOUNT' OR discount_value <= 100)
    ),
    CONSTRAINT ck_voucher_min CHECK (min_order_amount >= 0),
    CONSTRAINT ck_voucher_dates CHECK (end_date >= start_date),
    CONSTRAINT ck_voucher_qty CHECK (quantity >= 0)
);

-- ============================================================
-- Invoice
-- status: 0 = pending (draft), 1 = paid, 2 = cancelled
-- payment_method: NULL while pending, required once paid
-- ============================================================
CREATE TABLE invoice (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    customer_id INT NOT NULL REFERENCES customer (id),
    employee_id INT NOT NULL REFERENCES employee (id),
    voucher_id INT REFERENCES voucher (id),
    total_amount NUMERIC(15, 0) NOT NULL DEFAULT 0,        -- before discount
    -- voucher value actually applied
    discount_amount NUMERIC(15, 0) NOT NULL DEFAULT 0,
    -- amount customer pays
    final_amount NUMERIC(15, 0) NOT NULL DEFAULT 0,
    payment_method VARCHAR(20),
    status VARCHAR(20) NOT NULL DEFAULT "PENDING",
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    paid_at TIMESTAMP,
    note TEXT,
    CONSTRAINT ck_invoice_status CHECK (
        status IN ('PENDING', 'PAID', 'CANCELLED')
    ),
    CONSTRAINT ck_invoice_method CHECK (
        payment_method IS NULL OR payment_method IN ('CASH', 'TRANSFER')
    ),
    CONSTRAINT ck_invoice_amounts CHECK (
        total_amount >= 0
        AND discount_amount >= 0
        AND discount_amount <= total_amount
        AND final_amount = total_amount - discount_amount
    ),
    CONSTRAINT ck_invoice_paid CHECK (
        status <> 1 OR (payment_method IS NOT NULL AND paid_at IS NOT NULL)
    )
);

CREATE TABLE invoice_item (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id INT NOT NULL REFERENCES invoice (id) ON DELETE CASCADE,
    variant_id INT NOT NULL REFERENCES product_variant (id),
    unit_price NUMERIC(15, 0) NOT NULL,            -- sale price at time of sale
    -- cost price at time of sale (for profit reports)
    cost_price NUMERIC(15, 0) NOT NULL,
    quantity INT NOT NULL,
    CONSTRAINT uq_invoice_variant UNIQUE (invoice_id, variant_id),
    CONSTRAINT ck_item_qty CHECK (quantity > 0),
    CONSTRAINT ck_item_prices CHECK (unit_price >= 0 AND cost_price >= 0)
);

-- ============================================================
-- Indexes (PostgreSQL does not index foreign keys automatically)
-- ============================================================
CREATE INDEX idx_variant_product ON product_variant (product_id);
CREATE INDEX idx_variant_color ON product_variant (color_id);
CREATE INDEX idx_variant_size ON product_variant (size_id);
CREATE INDEX idx_variant_material ON product_variant (material_id);
CREATE INDEX idx_variant_thickness ON product_variant (thickness_id);
CREATE INDEX idx_variant_supplier ON product_variant (supplier_id);
CREATE INDEX idx_invoice_customer ON invoice (customer_id);
CREATE INDEX idx_invoice_employee ON invoice (employee_id);
CREATE INDEX idx_invoice_voucher ON invoice (voucher_id);
CREATE INDEX idx_invoice_created ON invoice (created_at);
CREATE INDEX idx_invoice_paid_at ON invoice (paid_at);
CREATE INDEX idx_invoice_status ON invoice (status);
CREATE INDEX idx_item_invoice ON invoice_item (invoice_id);
CREATE INDEX idx_item_variant ON invoice_item (variant_id);
